
tasks:
  - name: deps
    init: |
      python3 -m pip install --no-cache-dir -r requirements.txt
      python3 -c "from app import db; db.create_all()"
    command: FLASK_ENV=development flask run


vscode:
  extensions:
    - alexcvzz.vscode-sqlite
