
tasks:
  - init: |
      python -m virtualenv venv
      source venv/bin/activate
      pip install --no-cache-dir -r requirements.txt
      python -c "from app import db; db.create_all()"
      deactivate
    command: |
      source venv/bin/activate
      FLASK_ENV=development flask run


vscode:
  extensions:
    - alexcvzz.vscode-sqlite
