
tasks:
  - init: |
      pip install --no-cache-dir -r requirements.txt
      python -c "from app import db; db.create_all()"
    command: FLASK_ENV=development flask run


vscode:
  extensions:
    - alexcvzz.vscode-sqlite
